import { QuizQuestion } from "../explore-syllabus";

export const DEMO_QUIZZES: QuizQuestion[] = [
  {
    question: "What is the primary function of an LLM at its core?",
    options: [
      "Running mathematical simulations",
      "Stitching databases of facts",
      "Predicting the next word in a sequence",
      "Searching the internet for answers",
    ],
    correctIndex: 2,
  },
  {
    question: "What is an AI 'hallucination'?",
    options: [
      "A visualization generated by the AI",
      "When the AI confidently presents false information as reality",
      "A feature that allows AI to analyze human dreams",
      "A system process crash",
    ],
    correctIndex: 1,
  },
  {
    question: "Which mechanism allows Transformers to understand the context between distant words in a sentence?",
    options: [
      "Temperature scaling",
      "Tokenization",
      "Neural dropping",
      "The Attention mechanism",
    ],
    correctIndex: 3,
  },
  {
    question: "What does 'Zero-Shot' prompting mean?",
    options: [
      "Providing one perfect example",
      "Asking a model to perform a task without any examples",
      "Limiting the output to zero words",
      "Fine-tuning a model on zero labeled data",
    ],
    correctIndex: 1,
  },
  {
    question: "Why might an LLM struggle to tell you how many 'R's are in the word 'Strawberry'?",
    options: [
      "It reads the word as a single 'token' rather than individual letters",
      "It doesn't care about spelling",
      "It is an open-source model limitation only",
      "It only processes numerical data",
    ],
    correctIndex: 0,
  },
];
